---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: latest

inputs:
- name: zipcloud
- name: zipcloud-pipeline

run:
  path: zipcloud-pipeline/zipcloud/scripts/unit-tests.sh